parser: babel-eslint
extends: airbnb
settings:
  import/resolver:
    meteor:
      extensions: [.js, .jsx]
rules:
  import/extensions: [off, never]
  import/no-absolute-path: [off, never] 
  no-underscore-dangle:
    - error
    - allow: [_id]